COLUMN_DISPLAY_NAMES = {
    'StarSystem': 'System',
    'BodyName': 'Body',
    'PlanetClass': 'Planet Class',
    'Landable': 'Landable',
    'DistanceFromArrivalLS': 'Distance (ls)',
    'SurfaceGravity': 'Gravity (g)',
    'SurfaceTemperature': 'Temperature (K)',
    'Atmosphere': 'Atmosphere',
    'AtmosphereType': 'Atmosphere Type',
    'Volcanism': 'Volcanism',
    'TerraformState': 'Terraform State',
    'Signals': 'Signals',
    'Discovery': 'Discovery',
    'Composition': 'Composition',
    'Ring': 'Ring',
    'Rings': 'Rings',
    'Radius': 'Radius (km)',
    'OrbitalPeriod': 'Orbital Period (d)',
    'SemiMajorAxis': 'Semi-Major Axis (km)',
    'Eccentricity': 'Eccentricity',
    'Inclination': 'Inclination (°)',
    'Periapsis': 'Periapsis (°)',
    'AxialTilt': 'Axial Tilt (°)',
    'MassEM': 'Mass (Earths)',
    'ReserveLevel': 'Reserve Level',
    'TidalLock': 'Tidal Lock',
    'Luminosity': 'Luminosity',
    'Age_MY': 'Age (MY)',
    'StellarMass': 'Stellar Mass',
    'AbsoluteMagnitude': 'Abs. Magnitude',
    'RotationPeriod': 'Rotation Period (d)',
    'ScanType': 'Scan Type',
    'Species': 'Species',
    'Genus': 'Genus',
    'Variant': 'Variant',
    'Sample': 'Sample',
    'SampleType': 'Sample Type',
    'SampleCount': 'Sample Count',
    'BioType': 'Bio Type',
    'BioSignal': 'Bio Signal',
    'BioLocation': 'Bio Location',
    'BioDistance': 'Bio Distance',
    'BioName': 'Bio Name',
    'BioGenus': 'Bio Genus',
    'BioVariant': 'Bio Variant',
    'Abandoned': 'Abandoned',
    'Active': 'Active',
    'Alliance': 'Alliance',
    'AllowNotorious': 'Allow Notorious',
    'Amount': 'Amount',
    'AscendingNode': 'Ascending Node',
    'AvgPricePaid': 'Average Price Paid',
    'Bank_Account': 'Bank Account',
    'BaseValue': 'Base Value',
    'BlackMarket': 'Black Market',
    'Body': 'Body',
    'BodyCount': 'Body Count',
    'BodyID': 'Body ID',
    'BodyType': 'Body Type',
    'Bonus': 'Bonus',
    'BoostUsed': 'Boost Used',
    'Bounty': 'Bounty',
    'BuyPrice': 'Buy Price',
    'CGID': 'Community Goal ID',
    'CQC': 'CQC',
    'CarrierID': 'Carrier ID',
    'CarrierName': 'Carrier Name',
    'CarrierType': 'Carrier Type',
    'Category': 'Category',
    'Category_Localised': 'Category (Localized)',
    'Channel': 'Channel',
    'Collision': 'Collision',
    'Commander': 'Commander',
    'Commodity': 'Commodity',
    'Commodity_Localised': 'Commodity (Localized)',
    'Components': 'Components',
    'Conflicts': 'Conflicts',
    'ControllingPower': 'Controlling Power',
    'Cost': 'Cost',
    'Count': 'Count',
    'Crafting': 'Crafting',
    'Credits': 'Credits',
    'CurrentGoals': 'Current Goals',
    'CurrentRank': 'Current Rank',
    'CurrentRankName': 'Current Rank Name',
    'Data': 'Data',
    'DepartureTime': 'Departure Time',
    'DistFromStarLS': 'Distance from Star (ls)',
    'Docked': 'Docked',
    'DockingAccess': 'Docking Access',
    'Donation': 'Donation',
    'Engineers': 'Engineers',
    'EntryID': 'Entry ID',
    'Exobiology': 'Exobiology',
    'Expiry': 'Expiry',
    'Log': 'Log',
    'Faction': 'Faction',
    'FactionEffects': 'Faction Effects',
    'Factions': 'Factions',
    'FuelCapacity': 'Fuel Capacity',
    'FuelLevel': 'Fuel Level',
    'FuelMain': 'Main Fuel',
    'FuelReservoir': 'Fuel Reservoir',
    'FullyRepaired': 'Fully Repaired',
    'GameMode': 'Game Mode',
    'Group': 'Group',
    'Health': 'Health',
    'Horizons': 'Horizons',
    'Independent': 'Independent',
    'Influence': 'Influence',
    'Inventory': 'Inventory',
    'IsNewEntry': 'Is New Entry',
    'IsStation': 'Is Station',
    'Items': 'Items',
    'JumpDist': 'Jump Distance',
    'JumpRange': 'Jump Range',
    'KillerName': 'Killer Name',
    'KillerRank': 'Killer Rank',
    'KillerShip': 'Killer Ship',
    'KillerShipID': 'Killer Ship ID',
    'Latitude': 'Latitude',
    'LegalStatus': 'Legal Status',
    'Longitude': 'Longitude',
    'MarketID': 'Market ID',
    'Materials': 'Materials',
    'MissionID': 'Mission ID',
    'Missions': 'Missions',
    'Module': 'Module',
    'Module_Localised': 'Module (Localized)',
    'Name_Localised': 'Name (Localized)',
    'Notorious': 'Notorious',
    'OnFoot': 'On Foot',
    'Outfitting': 'Outfitting',
    'OwnerName': 'Owner Name',
    'Passengers': 'Passengers',
    'Percent': 'Percent',
    'PilotName': 'Pilot Name',
    'PilotRank': 'Pilot Rank',
    'PlanetRadius': 'Planet Radius',
    'Power': 'Power',
    'Powerplay': 'Powerplay',
    'Price': 'Price',
    'Rank': 'Rank',
    'Reputation': 'Reputation',
    'Reward': 'Reward',
    'Role': 'Role',
    'ScanStage': 'Scan Stage',
    'SellPrice': 'Sell Price',
    'ShipID': 'Ship ID',
    'ShipName': 'Ship Name',
    'ShipType': 'Ship Type',
    'SignalName': 'Signal Name',
    'SignalName_Localised': 'Signal Name (Localized)',
    'SignalType': 'Signal Type',
    'SquadronID': 'Squadron ID',
    'StarPos': 'Star Position',
    'StationFaction': 'Station Faction',
    'StationName': 'Station Name',
    'StationType': 'Station Type',
    'Status': 'Status',
    'SystemAddress': 'System Address',
    'Target': 'Target',
    'Target_Localised': 'Target (Localized)',
    'ThargoidLevel': 'Thargoid Level',
    'Type': 'Type',
    'Value': 'Value',
    'Wanted': 'Wanted',
    'WingName': 'Wing Name',
    'WasDiscovered': 'Discovered',
    'WasMapped': 'Mapped',
    'WasFootfalled': 'Footfall',
    'SurfacePressure': 'Surface Pressure',
    'MeanAnomaly': 'Mean Anomaly',
    'OrbitalInclination': 'Orbital Inclination',
    'Periapsis': 'Periapsis (°)',
    'RotationPeriod': 'Rotation Period (d)',
    'AxialTilt': 'Axial Tilt (°)',
    'SemiMajorAxis': 'Semi-Major Axis (km)',
    'Eccentricity': 'Eccentricity',
    'OrbitalPeriod': 'Orbital Period (d)',
    'AscendingNode': 'Ascending Node',
    'System': 'System',
    'Distance': 'Distance (ls)',
    'BodyID': 'Body ID',
    'PlanetClass': 'Planet Class',
    'AtmosphereType': 'Atmosphere Type',
    'AtmosphereComposition': 'Atmosphere Composition',
    'Mass': 'Mass (Earths)',
    'Radius': 'Radius (km)',
    'Gravity': 'Gravity (g)',
    'Temperature': 'Temperature (K)',
    'Materials': 'Materials',
    'Composition': 'Composition',
    'Volcanism': 'Volcanism',
    'TidalLock': 'Tidal Lock',
    'TerraformState': 'Terraform State',
    'ScanType': 'Scan Type',
    'Signals': 'Signals',
    'Parents': 'Parents',
    'event': 'Event',
    'timestamp': 'Timestamp',
    'Body': 'Body',
    'SystemAddress': 'System Address',
}
